---

- name: node | create an instances
  gcp_compute_instance:
    name: "{{ prefix_name }}-nat-gateway-node"
    machine_type: "{{ default_machine_type_02 }}"
    can_ip_forward: yes
    disks:
    - auto_delete: true
      boot: true
      initialize_params:
        disk_size_gb: 15
        source_image: "{{ubuntu18_source_image}}"
    zone: "{{ default_region }}-a"
    project: "{{ project_id }}"
    auth_kind: "{{ authkind }}"
    service_account_file: "{{ serviceaccount_dir }}/{{ serviceaccount_name }}"
    network_interfaces:
      - network: "{{ vpc }}"
        subnetwork: "{{ subnet01 }}"
        network_ip: "10.24.0.12"
        access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
    state: "{{ default_resource_state }}"
  register: node_nat_gateway

- name: debug of var
  debug:
    var: node_nat_gateway

- name: node | add tags to instance
  gce_tag:
    instance_name: "{{ node_nat_gateway.name }}"
    service_account_email: "{{ serviceaccount_email }}"
    pem_file: "{{ serviceaccount_dir }}/{{ serviceaccount_name }}"
    project_id: "{{ project_id }}"
    tags: "{{ item }}"
    zone: "{{ default_region }}-a"
    state: "{{ default_resource_state }}"
  with_items:
    - "{{ standard_fw_rule.targetTags }}"
    - "{{ allinternal_fw_rule.targetTags }}"

- name: node | add ssh keys to instance
  shell: "{{ item }}"
  with_items:
    - gcloud auth activate-service-account "{{serviceaccount_email}}" --key-file="{{ serviceaccount_dir }}/{{ serviceaccount_name }}" --project="{{project_id}}"
    - gcloud compute instances add-metadata "{{ node_nat_gateway.name }}" --zone="{{ default_region }}-a" --metadata-from-file ssh-keys="{{ssh_dir}}/{{ssh_filename}}"
    - gcloud auth revoke "{{serviceaccount_email}}"

