image: docker:17.04

services:
  - docker:dind

stages:
  - build-ci
  - build
  - deploy

variables:
  REGISTRY_URL: "registry.gitlab.com"
  IMAGE_PATH: ${REGISTRY_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:tmp
  IMAGE_BRANCH_PATH: ${REGISTRY_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}_${CI_COMMIT_BEFORE_SHA}
  IMAGE_STABLE_PATH: ${REGISTRY_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:stable
  IMAGE_LATEST_PATH: ${REGISTRY_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest

before_script:
  - echo $REGISTRY_URL
  - echo $IMAGE_PATH
  - echo $IMAGE_BRANCH_PATH
  - echo $IMAGE_STABLE_PATH
  - echo $IMAGE_LATEST_PATH
  - echo $CI_BUILD_TOKEN

build-ci:
  stage: build-ci
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL
    - docker build --pull -t $IMAGE_PATH .
    - docker push $IMAGE_PATH
  only:
    - master
    - develop

# Add every branch name to this stages
build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL
    - docker pull $IMAGE_PATH
    - docker tag $IMAGE_PATH $IMAGE_BRANCH_PATH
    - docker push $IMAGE_BRANCH_PATH
  dependencies:
    - build-ci
  only:
    - master
    - develop

build-latest:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL
    - docker pull $IMAGE_PATH
    - docker tag $IMAGE_PATH $IMAGE_LATEST_PATH
    - docker push $IMAGE_LATEST_PATH
  only:
    - master
    - develop

build-stable:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL
    - docker pull $IMAGE_PATH
    - docker tag $IMAGE_PATH $IMAGE_STABLE_PATH
    - docker push $IMAGE_STABLE_PATH
  only:
    - master

